# general
tap "ankitpokhrel/jira-cli", trusted: true
tap "1password/tap", trusted: true

# personal
tap "koekeishiya/formulae", trusted: true # yabai
tap "felixkratz/formulae", trusted: true  # borders

# general
brew "tldr"
brew "ack"
brew "bash"
brew "bash-completion"
brew "bat"
brew "btop"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "jq"
brew "ripgrep"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-vi-mode"
brew "glow"
brew "lnav"

# languages
brew "python"
brew "go"
brew "perl"
brew "php"
brew "nodenv"
brew "rbenv"
brew "ruby"
brew "erlang"
brew "elixir"

# personal
brew "neovim"
brew "lazygit"
brew "lazydocker"
brew "nvimpager"
brew "universal-ctags"
brew "zoxide"
brew "task"
brew "ast-grep"
brew "taskwarrior-tui"
brew "felixkratz/formulae/borders"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# general
# cask "hammerspoon", not needed right now
# cask "1password", come installed usually
cask "1password-cli"

# work
cask "postman"
brew "jira-cli"

# personal
cask "jordanbaird-ice"
cask "font-jetbrains-mono-nerd-font"
cask "font-departure-mono-nerd-font"
cask "font-noto-sans-mono-cjk-sc"
cask "font-noto-sans-mono-cjk-tc"
cask "font-noto-sans-mono-cjk-jp"
cask "font-noto-sans-mono-cjk-kr"
cask "appcleaner"
cask "betterzip"
# cask "ubersicht", not very useful
# install "amphetamine" from AppStore
cask "keycastr"
cask "wezterm"
cask "arc"
cask "alt-tab"
