# general
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "1password/tap"
# personal
tap "koekeishiya/formulae" # yabai
tap "felixkratz/formulae"  # borders

# general
brew "tldr"
brew "ack"
brew "bash"
brew "bash-completion"
brew "bat"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "jq"
brew "ripgrep"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-vi-mode"
brew "glow"

# languages
brew "python"
brew "go"
brew "perl"
brew "php"
brew "nodenv"
brew "rbenv"
brew "ruby"

# personal
brew "neovim"
brew "nvimpager"
brew "universal-ctags"
brew "zoxide"
brew "task"
brew "taskwarrior-tui"
brew "felixkratz/formulae/borders"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# general
cask "hammerspoon"
cask "1password"
cask "1password-cli"

# work
cask "postman"

# personal
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "appcleaner"
cask "betterzip"
# install amphetamin instead
cask "dozer"
cask "keycastr"
cask "wezterm"
cask "obsidian"
cask "arc"
cask "alt-tab"
